README.MD, client.go, client_test.go, message.go, message_test.go
* merged @awormuth changes from #17 
* added client.Whisper method for private messages
* test whispering with the client
* test parsing whisper messages
Waiting on quick feedback from @awormuth before merging
=> Whisper support

.travis.yml, README.MD, client.go, client_test.go, message.go, message_test.go
Thinking of removing autoreconnect again because it's a really bad implementation and makes the code a lot more complicated. It also didn't work for me when trying to keep a connection alive for several days.
=> Revert ping

client_test.go, test_resources/runtestsloop.sh
Biggest thing I've done in this PR is move the "mock server" code into one slightly modular function instead
Fixes #8
=> Simplify test cases

client.go, client_test.go, message.go
Notably, this is how you can check for mod status.
=> Add support for USERSTATE messages.

README.MD, client.go, helpers_test.go, message.go, message_test.go
=> Time parsing

README.MD, client.go, client_test.go, message.go
=> Implement NOTICE message handler

client.go, client_test.go
I'm not 10000000% sure about what the RECONNECT message looks like since I haven't captured it in the wild myself, but this looks to be the correct way to catch it by looking at other IRC libraries
Fixes #59
=> Implement RECONNECT handling

client.go, client_test.go, helpers_test.go
=> Handle "Invalid NICK" message sent from twitch

client.go, client_test.go, helpers_test.go
=> Pajlada implement ping

message.go
to make `go vet` happy and to clarify what it's used for
=> Add a comment to the UNSET message type

client_test.go
=> fix spelling mistake: received instead of recieved

.travis.yml, client.go, client_test.go, cmd/pingpong/.gitignore, cmd/pingpong/pingpong.go, run-test-tests.sh
Sorry for the big commits, and random fixing of other things in the same PR. this made it a lot easier to do proper stability testing of the changes I had made
I would like to test this a bit before deeming it safe for merge, but checking what I've done and asking questions is encouraged
=> Overhaul connection management

.travis.yml
=> test ignoring full file path

client.go, client_test.go
=> Send whispers in own channel instead of #jtv

client.go, client_test.go, message.go
User can now RECONNECT messages and NAMES response
We now 99% rely on the ParseMessage function to parse Messages for us, no longer relying on "strings contains" stuff at the bottom of the handleLine function (we still have ping/pong handling at the top yet to be fixed)
One consequence for this is that we will pass through more UNSET messages than before. This is because Twitch sends us a bunch of numeric-type messages that we don't really care about (see https://www.alien.net.au/irc/irc2numerics.html)
=> Treat more messages like real messages

message.go
fixes https://github.com/gempir/go-twitch-irc/issues/94
=> fix parseNames behavior when joining Room

client.go
PR for master branch: #90 
As discussed in #90 this is the same patch but requesting to merge into `dev`, not `master`
=> Request capabilities before login to get GLOBALUSERSTATE (dev branch)

README.MD, client.go, client_test.go, message.go, message_test.go
=> Add CLEARMSG message type

client.go
Should be a bit faster to get connections running with this
=> Request capabilities in one message instead of 3

client.go, tatombool.go, tatombool_test.go
also made some shitty tests for it so i could change the implementation after suggestions from the golangci-lint tool
=> Move tAtomBool helper class to its own file

client_test.go
Added a new test which tests the connectivity from start to finish.
It ensures that a disconnect happens as expected both from the server and client perspective.
It's a little more verbose, so I've added a few more "helper functions", which might seem excessive for now but should be healthy once more tests use this more full template
I'd like a review before going on and removing the `startServer2` part and just making that the default.
=> Improve base test structure

README.MD, client.go, client_test.go
=> Add a constructor for anonymous usage

.golangci.yml
doesn't work for us when we have so many message WAAAAAAAAAAY exceeding
reasonable amounts
=> Disable long line linter

message.go, message_test.go
added a test which fails before, but doesn't fail now
=> Double check emote data sent from twitch

README.MD, client.go, client_test.go, message.go, message_test.go
=> add GLOBALUSERSTATE support

message.go, message_test.go
Relevant Twitch issue: https://github.com/twitchdev/issues/issues/104
Fixes #140
=> We now handle VERY wrong emote indices

client.go
fixes #142
https://github.com/gempir/go-twitch-irc/blob/f799cc0ce17b6d5836fbf7b2d855bd66ffa38504/client.go#L1042-L1060
=> prevent writing to a nil when map is not initilized from join yet

client.go, client_test.go, ratelimit.go
- the Ratelimiter could be called multiple times when used by multiple clients #171 
- Use an interface instead so anyone can provide Ratelimiter
=> Ratelimiter Interface and mutex

README.MD, client.go, client_test.go
Remove the membership capability as discusssed in #128 and #126
=> remove membership as default capability #128 #126

client.go, client_test.go, message.go, message_test.go
This adds support for the native reply feature, see issue #158
=> Added support for replies

README.MD, client.go, client_test.go
Spend some time for googling and reviewing Twitch docs, NodeJs Twitch library to find out how to delete only one chat message. It can be usefull for someone else. Also I added missed func names to readme file
=> Add DeleteMessage function

client.go
this can cause reconnect loops
Fixes #197
=> fix: failed login can return a message we don't handle
