client.go

Enable TcpKeepAlive to ensure connections stay alive longer.

use TcpKeepAlive

---

README.MD
client.go
client_test.go
message.go
message_test.go

This improves upon #25 by adding an interval that can be shortened for tests.  Feel free to reject and/or improve upon this if this approach is too messy.

WIP: add onNewReconnectMessage and improve test coverage

---

message.go
message_test.go

Twitch /me messages also append a \u0001 character at the end of the message. This was not parsed properly.
The changes fix the issue, and the test case for action messages has been updated.
Minimal test to show the bug in the last version
Join the chat at https://twitch.tv/pajlada/chat and type an Action message (i.e. `/me test`) and you will see the issue
```go
package main
import (
"fmt"
"github.com/gempir/go-twitch-irc"
)
func main() {
client := twitch.NewClient("justinfan695", "oauth:kjhdfgj")
client.OnNewMessage(func(channel string, user twitch.User, message twitch.Message) {
if message.Action {
fmt.Printf("'%s' will incorrectly end with a \u0001\n", message.Text)
}
})
client.Join("pajlada")
err := client.Connect()
if err != nil {
panic(err)
}
}
```

Fix ACTION (/me) parsing

---

message.go
message_test.go

This fixes normal `/clear` commands, since previously `OnNewClearchatMessage` only triggered when someone was timed out

Fix clearchat parsing

---

client.go
client_test.go

Had the problem that if I copy-pasted channel names from Twitch that contained uppercase characters ( DisguisedToastHS ), it didn't error out or gave me any warning, it just didn't give me any messages.
One approach is to just make the argument in Client.Join lowercase in the beginning.
What do you think?
``` go
func main() {
c := twitch.NewClient("tinee", "oauth:abcdefg")
c.OnNewMessage(func(channel string, user twitch.User, message twitch.Message) {
fmt.Println(message.Text)
})
// This will not work because all channels is lowercase.
c.Join("DisguisedToastHS")
c.Connect()
}
```

Client.Join is not case sensitive.

---

README.MD
client.go
client_test.go
helpers_test.go
message.go
message_test.go

- added support for twitch irc [membership](https://dev.twitch.tv/docs/irc/membership/), keeping a userlist that's updated on every `NAMES`, `JOIN` and `PART`
- exposed a new `Client` method which returns the current userlist for a given channel:
```go
client.Userlist(channel string) []string
```
- added `OnUserJoin` and `OnUserPart` callbacks, giving the channel and user to the caller, allowing for things like join/part messages or other custom handling _(the user param here has to be a string here as the join/part messages contain next to no info, so I couldn't use the `User` struct unless we want to fill it with mostly dummy/assumed info)_
also added tests for everything and a new test helper for string slices, all tests pass for me and everything in some trivial tests, should close …

Add support for membership, exposing a userlist and joins/parts callbacks

---

client.go
client_test.go
message.go

Previously, any messages that didn't parse their messageType properly
would just leave the MessageType as the default (which was WHISPER)
- Add a "developer" `OnNewUnsetMessage` function.
this is useful for finding messages that don't parse properly in go-twitch-irc.

Add new MessageType UNSET, which is now the default MessageType

---

client.go
client_test.go

Parsing should be fine, only thing I could imagine being contested is whether the error should be split up into two: Login authentication failed and Improperly formatted auth
Fixes #55

Error out from Connect on bad/malformed oauth

---

client.go
client_test.go

Useful if a token has been invalidated, and a new one has been generated

Add a function for changing the irc token of a client

---

go.mod

Resolves #80 
This will allows users with Go 1.11.0+ to control when they upgrade their libraries/binaries to the next major version, even after we've merged it into master.
When we are ready to release v2.0.0, we just need to update the first line to include `/v2` at the end, and then increment it for future MAJOR releases.
In Go 1.12, the go.mod file indicates the version of the language used by the files within that module. However, this makes it [not compatible with 1.11.3](https://github.com/golang/go/issues/30446#issuecomment-468044008) or earlier. As we don't use any 1.12 features, I've removed the line.
For more information about how to work with Go Modules, read [this](https://roberto.selbach.ca/intro-to-go-modules/).

Implement Go Modules

---

README.MD
client.go
client_test.go
cmd/pingpong/pingpong.go

new style is updated in the README.md file
```go
client.OnConnect(func() {})
client.OnPrivateMessage(func(message PrivateMessage) {})
client.OnWhisperMessage(func(message WhisperMessage) {})
client.OnClearChatMessage(func(message ClearChatMessage) {})
client.OnRoomStateMessage(func(message RoomStateMessage) {})
client.OnUsernoticeMessage(func(message UserNoticeMessage) {})
client.OnUserstateMessage(func(message UserStateMessage) {})
client.OnNoticeMessage(func(message NoticeMessage) {})
client.OnUserJoinMessage(func(message UserJoinMessage) {})
client.OnUserPartMessage(func(message UserPartMessage) {})
```

rename callbacks to be more uniform

---

client.go

If CAP REQs are sent after login, the server doesn't send us our own `GLOBALUSERSTATE`
https://dev.twitch.tv/docs/irc/tags/#globaluserstate-twitch-tags
Also a callback/parser might be required to support `GLOBALUSERSTATE` messages

Request capabilities before login to get GLOBALUSERSTATE

---

message.go
message_test.go

Fixes #67 
The recoverMessage function helped identify offending messages, and should prevent similar issues in the future killing clients.
At the moment, it logs the raw message, error, and stack trace to console. If wanted, we could write it to an error.logs file. That way we can simply review it at the end of the session, instead of keeping an eye on the console.

Fixes #67 and adds recoverMessage function

---

go.mod

If the module is version v2 or higher, the major version of the module must be included as a /vN at the end of the module paths used in go.mod files (e.g., module github.com/my/mod/v2, require github.com/my/mod/v2 v2.0.0) and in the package import path (e.g., import "github.com/my/mod/v2/mypkg").
Source: https://github.com/golang/go/wiki/Modules#semantic-import-versioning

Update go.mod to reflect v2.0.0

---

irc.go

Sanity check the bounds before accessing all of the split fields.
Fixes #109

Gracefully handle smaller message sources.

---

client.go
client_test.go

The rejoin functionality of go-twitch-irc was broken in a #105 or #106 
this should fix it

Rejoin properly

---

go.mod

After trying to build the repo with various go versions (in the github ci test branch) I've come to the conclusion that the library does not build with Go below version 1.12.
This should be reflected in the `go.mod` file as done in this PR.

Set minimum go version to 1.12

---

README.MD
client.go
client_test.go

caps can be modified by changing the clients .Caps member before
connecting.
See tests for example
Use the const values when making your own list of caps to send along
Note that the default caps we send might change in the future
Works on #126 
I don't think this PR is the right time to change the default Caps, but with this in place I think we're better prepared to change them.

Make caps modifiable

---

message.go
message_test.go

This small PR fixes emote parsing from `/me` messages.
At the moment if we have text `/me Test Kappa`, the emote will be parsed from `privateMessage.Message = "\u0001ACTION Test Kappa"` and after this `privateMessage.Message` will be overwritten with `Test Kappa`, so `privateMessage.Emotes[0]` will have a wrong shift.

Fixed emote parsing from action messages.

---

client.go
client_test.go

Resolves issue #137:
- `RestrictChatForFollowers`: Runs twitch `/followers` command with channel and duration arguments
- `AllowChatForEverybody`: Runs twitch `/followersoff` command with channel argument

Add commands RestrictChatForFollowers and AllowChatForEverybody

---

message.go
message_test.go

This CL adds a new field called Positions to the Emote struct. Positions is a list of EmotePosition, which marks the start and end character of an emote, as sent by the Twitch API.
This allows for downstream consumers of this library to quickly replace emotes in text, without the need to parse/regex the message string.

Added emote position extraction to emote parse.

---

client.go
helpers_test.go
message.go
message_test.go

Twitch now sends to moderators and stream owners a new tag with all chat messages, "first-msg=N" where N is 0 or 1. If it's 1, this is the first time this user chatted on the target user's stream. This CL adds support for parsing that tag, and adds a new boolean to the private message struct called FirstMessage to reflect this status.

Added First Message support to Twitch user messages.

---

message_test.go

- Move the test message to its own variable
- Use escape sequences instead of literal unicode control character
- consistent spacing with other tests

Suggestions for the outofbounds PR

---

client.go
client_test.go
helpers_test.go
ratelimit.go

Ratelimiting implemented based on a slice with times in it. All the other examples of sliding window implementations looked super complicated to me and not so straight forward.
I'm not sure if this is the correct way to solve this problem, but at least my tests run now. Which they haven't done for any implementation before as you can see by the build history.
One slight weird thing still is I added a 100ms extra sleep, because on CI it kept failing, locally I could run it fine. This is slightly alarming because I'm wondering if on different systems it could behave even differently.
But running `go test -race` brings up no issues.

fix #164 and respect ratelimit for bulk joins

---

README.MD
client.go
client_test.go

Not sure if it's good to invoke the client callbacks within handle functions for JOIN/PART but it just seemed the simplest.
~~I'm not familiar with library's code much, thus I don't have a good idea about what potentially relevant tests I could add, but I'm open to experimenting and writing something.~~ thanks pajlada for help figuring that out
One small side-note I have: name of the callback `OnUserJoinMessage` might be confusing, indicating it's carrying JOIN message for our user because of the `User` part in its name (ideally `OnJoinMessage` and `OnSelfJoinMessage` would make most sense to me). I know that's the name that was there from the beginning but I think it's only confusing if anything.
That's nothing that I can change though, just pointing that out...
Closes #178

Add callbacks for self JOIN/PART messages

---

README.MD
client.go
client_test.go

Thought it would be useful to have a client function that returns ping latency like [dank-twitch-irc](https://github.com/kararty/dank-twitch-irc?tab=readme-ov-file#chatclient-api) does.

Add client function to return ping latency

---

client.go
message.go
message_test.go

Add mod/vip/broadcaster fields to User(#203)

Add mod/vip/broadcaster fields to User
